[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xcid"
version = "0.2"
description = "XC-ID: X Chromosome inactivation IDentifier"
readme = "README.md"

requires-python = ">=3.10"

dependencies = ["numpy>=2.2", 
                "pandas>=2.3", 
                "scipy>=1.15", 
                "statsmodels>=0.14", 
                "pysam>=0.23", 
                "joblib>=1.5",  
                ]

[project.scripts]
xcid = "xcid.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]